[package]
name = "pinocchio"
description = "Create Solana programs with no dependencies attached"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
readme = "./README.md"
repository = "https://github.com/febo/pinocchio"