[package]
name = "pinocchio"
description = "Create Solana programs with no dependencies attached"
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
readme = "./README.md"
repository = "https://github.com/febo/pinocchio"

[lints.rust]
unexpected_cfgs = {level = "warn", check-cfg = ['cfg(target_os, values("solana"))', 'cfg(target_feature, values("static-syscalls"))'] }